"""adding closeDate to Game table

Revision ID: 81be94f5920a
Revises: 410ea6e02ac2
Create Date: 2020-05-12 13:06:40.076914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81be94f5920a'
down_revision = '410ea6e02ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('closeDate', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'closeDate')
    # ### end Alembic commands ###
